export const jobList = [
  // Local Skilled Jobs
  "Tailor",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Mechanic",
  "Painter",
  "Hairdresser",
  "Barber",
  "Makeup Artist",
  "Caterer",
  "Baker",
  "Welder",
  "Bricklayer",
  "Dry Cleaner",
  "Event Decorator",
  "Driver",
  "Photographer",
  "Videographer",
  "Shoemaker",
  "Furniture Maker",

  // Tech & Professional Jobs
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "Data Scientist",
  "UI/UX Designer",
  "Product Manager",
  "Cloud Engineer",
  "Cybersecurity Specialist",
  "AI/ML Engineer",
  "DevOps Engineer",
  "Database Administrator",
  "IT Support Specialist",
  "Business Analyst",
];
